services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=todoDB
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
