name: Branch Protection

on:
  # Run when someone with admin rights pushes to main,
  # to ensure branch protection is always applied
  push:
    branches:
      - main
  # Run on schedule to ensure protection remains in place
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  # Allow manual trigger
  workflow_dispatch:

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      administration: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Configure branch protection for main branch
        run: |
          # Enable branch protection for main branch
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks='{"strict":true,"contexts":["build"]}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"dismissal_restrictions":{},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":1}' \
            -f restrictions=null
          
          echo "Branch protection rules applied successfully"